### ISSUE TITLE
[BUG] metrics names are overridden each other.

### ISSUE THREAD

**Issue by hayk96** [TomL-dev/graphite-exporter#19]
Hi @TomL-dev 👋
I have a configuration file, where `targets` are defined the following structure which is described below:

```yaml
targets:
  - name: metric_name_1
    graphite: graphite
    query: "<SOME QUERY>"

  - name: metric_name_2
    graphite: graphite
    query: "<SOME QUERY>" 
```

When the exporter runs it only exports the last metric, seems that the rest of the metric names are overridden by the last one.

e.g.  I am expecting the following result:
`metric_name_1{<label_name>="<label_value>"} 1`
`metric_name_2{<label_name>="<label_value>"} 1`

but getting the result like this:
`metric_name_2{<label_name>="<label_value>"} 2`

Thanks for building this project.
